
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BLFacadeImplementationService", targetNamespace = "http://businessLogic/", wsdlLocation = "http://0.0.0.0:1099/ws/Rides?wsdl")
public class BLFacadeImplementationService
    extends Service
{

    private final static URL BLFACADEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException BLFACADEIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName BLFACADEIMPLEMENTATIONSERVICE_QNAME = new QName("http://businessLogic/", "BLFacadeImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://0.0.0.0:1099/ws/Rides?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BLFACADEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        BLFACADEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public BLFacadeImplementationService() {
        super(__getWsdlLocation(), BLFACADEIMPLEMENTATIONSERVICE_QNAME);
    }

    public BLFacadeImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BLFACADEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public BLFacadeImplementationService(URL wsdlLocation) {
        super(wsdlLocation, BLFACADEIMPLEMENTATIONSERVICE_QNAME);
    }

    public BLFacadeImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BLFACADEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public BLFacadeImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BLFacadeImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BLFacade
     */
    @WebEndpoint(name = "BLFacadeImplementationPort")
    public BLFacade getBLFacadeImplementationPort() {
        return super.getPort(new QName("http://businessLogic/", "BLFacadeImplementationPort"), BLFacade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BLFacade
     */
    @WebEndpoint(name = "BLFacadeImplementationPort")
    public BLFacade getBLFacadeImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://businessLogic/", "BLFacadeImplementationPort"), BLFacade.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BLFACADEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw BLFACADEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return BLFACADEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
