
package service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RideMustBeLaterThanTodayException", targetNamespace = "http://businessLogic/")
public class RideMustBeLaterThanTodayException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RideMustBeLaterThanTodayException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RideMustBeLaterThanTodayException_Exception(String message, RideMustBeLaterThanTodayException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RideMustBeLaterThanTodayException_Exception(String message, RideMustBeLaterThanTodayException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: service.RideMustBeLaterThanTodayException
     */
    public RideMustBeLaterThanTodayException getFaultInfo() {
        return faultInfo;
    }

}
